/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author WINDA PURBA
 */
public class Formsuhu extends javax.swing.JFrame {

    /**
     * Creates new form Formsuhu
     */
    public Formsuhu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Nilai1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        celcius1 = new javax.swing.JRadioButton();
        fahrenheit1 = new javax.swing.JRadioButton();
        calvin1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        celcius2 = new javax.swing.JRadioButton();
        fahrenheit2 = new javax.swing.JRadioButton();
        calvin2 = new javax.swing.JRadioButton();
        hasil = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Nilai2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Nilai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nilai1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Input");

        jLabel2.setText("FROM");

        buttonGroup1.add(celcius1);
        celcius1.setText("Celcius");
        celcius1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celcius1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(fahrenheit1);
        fahrenheit1.setText("Fahrenheit");

        buttonGroup1.add(calvin1);
        calvin1.setText("Calvin");

        jLabel3.setText("TO");

        buttonGroup2.add(celcius2);
        celcius2.setText("Celcius");

        buttonGroup2.add(fahrenheit2);
        fahrenheit2.setText("Fahrenheit");

        buttonGroup2.add(calvin2);
        calvin2.setText("Calvin");

        hasil.setText("Calculate!");
        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });

        jLabel4.setText("Result");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(132, 132, 132)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Nilai1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(calvin1)
                                .addGap(79, 79, 79)
                                .addComponent(calvin2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(celcius1)
                                .addGap(75, 75, 75)
                                .addComponent(celcius2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fahrenheit1)
                                .addGap(57, 57, 57)
                                .addComponent(fahrenheit2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel4)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hasil)
                            .addComponent(Nilai2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Nilai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(celcius1)
                    .addComponent(celcius2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fahrenheit1)
                    .addComponent(fahrenheit2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calvin1)
                    .addComponent(calvin2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hasil)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Nilai2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Nilai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nilai1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nilai1ActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
        double masuk;
        float rumus;
        String keluar;
        
        masuk=Double.valueOf(Nilai1.getText());
            if(celcius1.isSelected()){
                if(celcius2.isSelected()){
                    rumus = (float) masuk;
                    keluar =String.valueOf(rumus);
                    Nilai2.setText(keluar);
                }
                if(fahrenheit2.isSelected()){
                    rumus = (float)((masuk*9/5)+32);
                   keluar = String.valueOf(rumus);
                    Nilai2.setText(keluar);
                }
                if(calvin2.isSelected()){
                    rumus = (float) (masuk + 273.15);
                    keluar = String.valueOf(rumus);
                    Nilai2.setText(keluar);
                }
                
            }
            else if(fahrenheit1.isSelected()){
                if(fahrenheit2.isSelected()){
                    rumus = (float) masuk;
                    keluar = String.valueOf(rumus);
                    Nilai2.setText(keluar);  
                }
                if(celcius2.isSelected()){
                    rumus = (float) ((masuk-32)/1.8);
                    keluar = String.valueOf(rumus);
                    Nilai2.setText(keluar);
                }
                if(calvin2.isSelected()){
                    rumus = (float) ((masuk+459.67)/1.8);
                    keluar = String.valueOf(rumus);
                    Nilai2.setText(keluar);
                }
            }
            else if(calvin1.isSelected()){
                if(calvin2.isSelected()){
                    rumus = (float) masuk;
                    keluar = String.valueOf(rumus);
                    Nilai2.setText(keluar);
                }
                if(fahrenheit2.isSelected()){
                    rumus = (float) ((masuk-273.15)*9/5+32);
                    keluar = String.valueOf(rumus);
                    Nilai2.setText(keluar);
                }
                if(celcius2.isSelected()){
                    rumus = (float) (masuk-273.15);
                    keluar = String.valueOf(rumus);
                    Nilai2.setText(keluar);
                }
                
            }
        
    }//GEN-LAST:event_hasilActionPerformed

    private void celcius1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celcius1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celcius1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formsuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formsuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formsuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formsuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formsuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nilai1;
    private javax.swing.JTextField Nilai2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton calvin1;
    private javax.swing.JRadioButton calvin2;
    private javax.swing.JRadioButton celcius1;
    private javax.swing.JRadioButton celcius2;
    private javax.swing.JRadioButton fahrenheit1;
    private javax.swing.JRadioButton fahrenheit2;
    private javax.swing.JButton hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
